vim.g.mapleader = " " -- Global leader key
vim.g.maplocalleader = " " -- Local leader key

vim.opt.number = true -- Show line numbers
vim.opt.relativenumber = true -- Show relative line numbers
vim.opt.mouse = "a" -- Enable mouse support
vim.opt.showmode = false -- Hide the current mode
vim.opt.clipboard = "unnamedplus" -- Use the system clipboard
vim.opt.breakindent = true -- Indent wrapped lines
vim.opt.undofile = true -- Persist undo history
vim.opt.ignorecase = true -- Ignore case in searches
vim.opt.smartcase = true -- Match case when uppercase is used
vim.opt.signcolumn = "yes" -- Always show the sign column
vim.opt.updatetime = 250 -- Reduce update delay
vim.opt.timeoutlen = 300 -- Set mapping timeout
vim.opt.splitright = true -- Open vertical splits to the right
vim.opt.splitbelow = true -- Open horizontal splits below
vim.opt.cursorline = true -- Highlight the current line
vim.opt.scrolloff = 8 -- Keep context around the cursor
vim.opt.termguicolors = true -- Enable true color support
vim.opt.confirm = true -- Confirm instead of failing commands
